name: Manually Retag Docker Image

on:
  workflow_dispatch:

jobs:
  retag:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull latest image
        run: |
          docker pull samsharma/java-docker-demo:latest

      - name: Tag image with today's date
        run: |
          DATE=$(date +%Y-%m-%d)
          docker tag samsharma/java-docker-demo:latest samsharma/java-docker-demo:v:$DATE

      - name: Push new tag
        run: |
          DATE=$(date +%Y-%m-%d)
          docker push samsharma/java-docker-demo:v:$DATE
